### ISSUE TITLE
Broken Binary - Linux release not working on Ubuntu 20.04

### ISSUE THREAD

**Issue by ghost** [dhogborg/rtl-gopow#17]
It's not working for me on Kubuntu 20.04 LTS, keeps saying: gopow: command not found as if the file didn't exist.

No options seem to work even if I give it the input file and output.

The only info I managed to get was when issuing a command "Open In Terminal":
`DATA[0000] load failed                                   error=missing input file`

I'll try building and compiling myself later.

EDIT: Typo FATA fixed to DATA, not sure how that happened.

**Comment by dhogborg** [comment]
Since you are able to start the app (indicated by `FATA[0000] load failed error=missing input file`) I can conclude that there is no problem with the binary.

Place the binary in a folder included in your `$PATH` and you should be good.
