### ISSUE TITLE
Doesn't build on Ubuntu i386

### ISSUE THREAD

**Issue by ghost** [dhogborg/rtl-gopow#2]
ton@MacMini:~/rtl-gopow$ go build
gopow.go:6:2: cannot find package "github.com/Sirupsen/logrus" in any of:
        /usr/src/pkg/github.com/Sirupsen/logrus (from $GOROOT)
        ($GOPATH not set)
gopow.go:7:2: cannot find package "github.com/codegangsta/cli" in any of:
        /usr/src/pkg/github.com/codegangsta/cli (from $GOROOT)
        ($GOPATH not set)
gopow.go:9:2: cannot find package "github.com/dhogborg/rtl-gopow/internal/gopow" in any of:
        /usr/src/pkg/github.com/dhogborg/rtl-gopow/internal/gopow (from $GOROOT)
        ($GOPATH not set)

**Comment by dhogborg** [comment]
Your GOPATH and workspace is not set up correctly, take a look at this document for creating a working golang workspace: https://golang.org/doc/code.html

Documentation specific to building rtl-gopow is in the works, but in a separate issue #.
