### ISSUE TITLE
Problem with time ticks

### ISSUE THREAD

**Issue by DE8MSH** [dhogborg/rtl-gopow#4]
Hi,

have a look at my rendered pictur , please. There's a problem with time ticks.

http://picpaste.de/pics/ae4eec7346dc61cf4b7a9a8ab283c436.1437592556.jpg

Thank you.

DE8MSH
Marco

**Comment by dhogborg** [comment]
Unable to replicate this, can you send me a sample file that exhibits this behaviour?

**Comment by dhogborg** [comment]
Closing since I can't replicate and don't have enough information to begin a debug. You are very welcome to provide a sample file that exhibits this behaviour and I will re-open the issue.
