### ISSUE TITLE
Difference when using concatenated data files vs concatenated images

### ISSUE THREAD

**Issue by shmick** [dhogborg/rtl-gopow#5]
I ran 5 x rtl_power scans for 10 minutes, each using a different gain (10, 20, 30, 40, 50)

```
for i in 10 20 30 40 50
do rtl_power -f 566M:608M:5k -e 10m -g $i -p 60 -i 1 -D 0 output-$i.log
done
```

Test 1: Process each file with gopow, ending up with 5 images. Use imagemagick to append the images into a single image.

Results: It looks like some sort of gain normalization routine is used, which results in 5 very similar looking images.

Test 2: Concatenate the 5 rtl_power data files into 1 large file and process the log file with gopow

Results: More of what I was expecting, with each scan getting more noisy as the gain is increased.

See image:

![gopow](https://cloud.githubusercontent.com/assets/1855990/12275524/78a6c244-b93e-11e5-85db-e67e5112f0fa.png)

**Comment by dhogborg** [comment]
Your observations are correct, the data is normalized ([table.go](https://github.com/dhogborg/rtl-gopow/blob/master/internal/gopow/table.go#L103)). 

This is something I can consider making optional, by letting the user specify the range manually.

**Comment by shmick** [comment]
That would be a nice feature to have. This is a great utility, thanks so much for making it available.

**Comment by dhogborg** [comment]
This feature is now available in the latest release. (1c915a237df0b1d19595b3e143c764a4f1614fd8)

**Comment by shmick** [comment]
Thanks for this. I'm already finding it to be a great help for being able to "zoom in" on things.
