### ISSUE TITLE
Feature request: Vertical markers

### ISSUE THREAD

**Issue by shmick** [dhogborg/rtl-gopow#6]
Would it be possible to have gopow create vertical markers every X pixels? The purpose is to create a visual separation of bandwidth groups in a heatmaps.

The example below is a heatmap of 470MHz through 698M with 125k bins. In this example, inserting a vertical line every 48 pixels ( 125KHz \* 48 = 6MHz for ATSC TV channels ) provides a great visualization of where each ATSC channel begins and ends. 

Thanks.

![atsc log2](https://cloud.githubusercontent.com/assets/1855990/12297299/8732a278-b9da-11e5-835f-f6975972335f.jpg)

**Comment by dhogborg** [comment]
Could be a nice feature. The tick-marks in general is something that I want to improve.
