### ISSUE TITLE
Feature request: Display pMax and pMin in image

### ISSUE THREAD

**Issue by shmick** [dhogborg/rtl-gopow#7]
Would it be possible to add the pMax and pMin values to the data in the bottom left of the image? It would also be nice to know if those values were the calculated values or the user supplied values.

Thanks.

**Comment by dhogborg** [comment]
This requires a bit more work than just adding more fields to the legend. In my view the legend is already taking up too much space and obscuring data when rendering smaller fields. This goes hand in hand with #6 , the annotation drawing needs to be looked over and improved. 

When the legend is placed outside the actual render we can add as much information as we want without obstructing data, and possibly do some configuration about which fields to include. 

In the meantime, the pMax and pMin values can be seen by providing the `--verbose` flag on render.
