### ISSUE TITLE
GoPow for Windows 32 bit OS

### ISSUE THREAD

**Issue by gl-Hub** [dhogborg/rtl-gopow#9]
Hello,

if possible please add a redy to run binary of GoPow for Windows 32 bit OS.

Thank you.

**Comment by dhogborg** [comment]
Added in bdc9dac911a3f777d363c02cca6dd21d179f5bc4

**Comment by dhogborg** [comment]
See https://github.com/dhogborg/rtl-gopow/releases/tag/v0.0.4 for release of win32 binary.

**Comment by gl-Hub** [comment]
Thank You !
